### PR TITLE
chore(deps): Upgrade CameraX to latest beta

### PR DESCRIPTION
**Pull request by mrousavy**
fixes some crashes

### CODE REVIEW

**Comment by mrousavy** [comment]
Hm, it fails because apparently the latest CameraX extensions package requires `minCompileSdk` version 33. We are on 31 and users already had issues with updating that....

**Comment by mrousavy** [comment]
```
* What went wrong:
[126](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:127)
Execution failed for task ':app:checkDebugAarMetadata'.
[127](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:128)
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[128](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:129)
   > The minCompileSdk (33) specified in a
[129](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:130)
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[130](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:131)
     is greater than this module's compileSdkVersion (android-31).
[131](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:132)
     Dependency: androidx.camera:camera-extensions:1.2.0-beta02.
[132](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:133)
     AAR metadata file: /home/runner/.gradle/caches/transforms-3/c8063b9fdb0866b1209a49661f8d1425/transformed/jetified-camera-extensions-1.2.0-beta02/META-INF/com/android/build/gradle/aar-metadata.properties.
[133](https://github.com/mrousavy/react-native-vision-camera/actions/runs/3226501837/jobs/5280096182#step:10:134)
```

**Comment by nikonhub** [comment]
Hello,

i've successfully managed to upgrade camerax to 1.2.0-rc0. After upgrading min sdk version to 33 which needed gradle 7.3.1 which needed kotlin version 1.6.20. While I understand that these steps might not be possible to do for everyone. Why don't let the user decide to modify the default camerax version as it is the case with kotlin version ?

Something like this :

```
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-guava:1.5.2"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2"

  implementation "androidx.camera:camera-core:$camerax_version"
  implementation "androidx.camera:camera-camera2:$camerax_version"
  implementation "androidx.camera:camera-lifecycle:$camerax_version"
  implementation "androidx.camera:camera-video:$camerax_version"

```

**Comment by mrousavy** [comment]
Hey @nikonhub!

That's because CameraX ships a ton of breaking changes, and I need to update VisionCamera pretty often because a new CameraX version often breaks stuff in my code.

**Comment by nikonhub** [comment]
I mean, of course keep the default version you want it to be.
But overridable like this is the case here 
gradle.properties

```
VisionCamera_kotlinVersion=1.5.30
```
build.gradle
```
  def kotlin_version = rootProject.ext.has('kotlinVersion') ? rootProject.ext.get('kotlinVersion') : project.properties['VisionCamera_kotlinVersion']
```

For example I got to clone your project just to use the 1.2.0-rc0 version, because there was a fix in it. It's not a big deal, but not the best solution either.

**Pull request closed without merging**
