### PR TITLE
[WIP] enable new arch

### PR DESCRIPTION
**Pull request by hannojg**

### CODE REVIEW

**Comment by mysport12** [comment]
Hi @hannojg,

I saw you already had this PR in progress and thought it might be easier to offer up a change needed for 0.76.0/new arch support since it modifies the CMakeLists.txt file which you are modifying here (in the spirit of reducing conflicts). Here is the patch I am running for 0.76.0. The conditional is one being applied by other libraries (https://github.com/Shopify/react-native-skia/pull/2694/files). The flag provided by RN is still not working even in 0.76.0-rc.5 but you can see the discussion regarding it here (https://github.com/react-native-community/discussions-and-proposals/discussions/816#)

```diff --git a/android/CMakeLists.txt b/android/CMakeLists.txt
index 1460dbd7729f1375852876f13af0e89c46c1382e..75b5d742ad754fc1b4ced77840ade71098ba1e84 100644
--- a/android/CMakeLists.txt
+++ b/android/CMakeLists.txt
@@ -54,15 +54,29 @@ target_include_directories(
         "${NODE_MODULES_DIR}/react-native/ReactAndroid/src/main/jni/react/turbomodule" # <-- CallInvokerHolder JNI wrapper
 )
 
-# Link everything together
-target_link_libraries(
-        ${PACKAGE_NAME}
-        ${LOG_LIB}                          # <-- Logcat logger
-        android                             # <-- Android JNI core
-        ReactAndroid::jsi                   # <-- RN: JSI
-        ReactAndroid::reactnativejni        # <-- RN: React Native JNI bindings
-        fbjni::fbjni                        # <-- fbjni
-)
+
+
+# This if-then-else can be removed once this library does not support version below 0.76
+if (ReactAndroid_VERSION_MINOR GREATER_EQUAL 76)
+        target_link_libraries(
+                ${PACKAGE_NAME}
+                ${LOG_LIB}
+                android
+                ReactAndroid::reactnative
+                ReactAndroid::jsi
+                fbjni::fbjni
+        )
+else()
+        # Link everything together
+        target_link_libraries(
+                ${PACKAGE_NAME}
+                ${LOG_LIB}                          # <-- Logcat logger
+                android                             # <-- Android JNI core
+                ReactAndroid::jsi                   # <-- RN: JSI
+                ReactAndroid::reactnativejni        # <-- RN: React Native JNI bindings
+                fbjni::fbjni                        # <-- fbjni
+        )
+endif()
 
 # Optionally also add Frame Processors here
 message("VisionCamera: Frame Processors: ${ENABLE_FRAME_PROCESSORS}!")```

**Comment by mysport12** [comment]
If you'd prefer a separate PR I can certainly go that route. Just let me know.

**Comment by hannojg** [comment]
Thanks for bringing this to my attention I will consider this!

**Comment by hannojg** [comment]
actually i'll close this PR for this one, but i'll keep your comments in mind.

- https://github.com/mrousavy/react-native-vision-camera/pull/3250

**Pull request closed without merging**
