### PR TITLE
[V2] Upgrade to RN72.6

### PR DESCRIPTION
**Pull request by iBotPeaches**
## What

This PR adds RN72 into /Example for testing confirmation of compatibility on the v2 branch as well as upgrading to the latest in reanimated v3.

## Changes

* Changes were made following upgrade guide, skipping anything was already pre-modified.
* This entails things like
  * Skipping Flipper
  * ESLint
  * Jest

## Tested on

* Galaxy A13 5G
* Pixel 7 Pro
* iPhone 13 Pro

## Related issues

Nothing related. I recently fixed frame processors on v2 on the example app here. I did this in hopes that it would fix our plugin (https://github.com/sourcetoad/vision-camera-plugin-barcode-scanner) and internal application that are still on v2.

I did this because our application, our sample plugin application and the vision sample application all had the same exact error of some form of `ReanimatedError: property: __scanQRCodes doesn't exist`

While I fixed the sample here - it did not solve the problem on our plugin or internal application. So once I realized our internal application was on RN72 and this was not, I upgraded the example to RN72 to presumably see an error. However, I did not which saddened me.

This points at an undiscovered error on my side with our plugin. So I figured I might as well upstream my work on v2 for RN72.

video attached of proof.

https://github.com/mrousavy/react-native-vision-camera/assets/611784/2a255ee3-ab1a-468c-9199-93eff018837c

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Oops. good thing for CI. Will work on that.

**Comment by mrousavy** [comment]
Thanks for your PR, Great stuff! Is this ready for review?

**Comment by iBotPeaches** [comment]
> Thanks for your PR, Great stuff! Is this ready for review?

Not yet, can't figure out Android CI failure. Still looking into it. Ignoring the JS lint failures as those have been broken since reanimated 3 merge.

**Comment by jeroenvanhattem** [comment]
Could we get some eyes on this? The updating of `react-native-reanimated` maybe fixes #2207 as well?

**Comment by iBotPeaches** [comment]
> Could we get some eyes on this? The updating of `react-native-reanimated` maybe fixes #2207 as well?

Eyes for what? This just updates the example app. I did this because I couldn't isolate the issues I had in our application. I wanted to use/update the example in order to replicate my problem.

I did, I submitted fix and then kinda put this on backburner. Updating the example RN version wouldn't do anything directly.

**Comment by iBotPeaches** [comment]
Closing as 72 is now outdated and if I revisit I'll jump to 73.

**Pull request closed without merging**
