### PR TITLE
feat: with gradle implementation

### LINKED ISSUE #2256: ❓ Waiting for the barcode module to be downloaded.
### Question

Hello,

On my app, I start the app with a Camera View directly after the splash screen.
The CameraView is set to get the Qrcode directly.
On my devices it works even after a fresh install but according to Google Console, when they test I get always 2 crashes on 7.

It was a bit tricky to understand why without logs but I added them and I get :

```
Camera.onError(unknown/unknown): [unknown/unknown] Waiting for the barcode module to be downloaded. Please wait. [unknown/unknown]: [unknown/unknown] Waiting for the barcode module to be downloaded. Please wait.
```

Actually, I am not reporting a bug, but more a strategy to adopt in this case. 
Since the error looks "unknown", what can it be, the best strategy to wait and to retry?

```
// The full error object
{
arguments: [
Camera.onError(unknown/unknown): [unknown/unknown] Waiting for the barcode module to be downloaded. Please wait., 
{
_cause: {}, 
_code: unknown/unknown, 
_message: [unknown/unknown] Waiting for the barcode module to be downloaded. Please wait., 
message: [unknown/unknown] Waiting for the barcode module to be downloaded. Please wait., 
name: unknown/unknown, 
stack: 
[unknown/unknown]: [unknown/unknown] Waiting for the barcode module to be downloaded. Please wait.
    at construct (native)
    at Wrapper (address at index.android.bundle:1:197548)
    at construct (native)
    at _createSuperInternal (address at index.android.bundle:1:2492550)
    at call (native)
    at CameraError (address at index.android.bundle:1:2493014)
    at construct (native)
    at _createSuperInternal (address at index....
}
]
}
```

Thank you!

### What I tried

_No response_

### VisionCamera Version

3.6.13

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

### PR DESCRIPTION
**Pull request by erwanlpfr**
## What

A conditional config to add the MLKit feature to android.
Now there are two ways : 
 - Default and previous one by adding a line in android manifest
 - Other one to edit the `app/build.gradle` with implementation line

`true` does the same as before and it does not break any installations.

Let me know if there is any doubts.

Thanks for your work as always!

## Tested on

My own install/build. It correctly patches the `app/build.gradle`.

## Related issues

closes https://github.com/mrousavy/react-native-vision-camera/issues/2256

### CODE REVIEW

**Comment by mrousavy** [comment]
Amazing !!! 

Thanks so much for this, this has been on my TODO list for a while.

Two things:

1. I'll add docs to this later.
2. Is there any way we can create tests for the config plugins?

**Comment by erwanlpfr** [comment]
Actually, no idea how to make a test for this.
The `app/buiid.gradle` is considered as dangerous by Expo (https://docs.expo.dev/config-plugins/plugins-and-mods/#android). 
RN Firebase is using this since a while and I guess it is working, also.

Let's see if they add it later!

**Comment by kyjus25** [comment]
Needless to say, excited for this to get released so I can do builds 😅 I'm not savvy enough to compile this manually. Thanks a ton, both of you

**Comment by mrousavy** [comment]
Hey - thanks for the PR again, I just had another idea after merging it- check this out, this should be more stable than a regex replace: https://github.com/mrousavy/react-native-vision-camera/pull/2355

**Comment by erwanlpfr** [comment]
Hello! I saw it and it is way better !
Thanks!!

**Pull request merged**
