### PR TITLE
fix: Fix PreviewView being stretched

### LINKED ISSUE #452: 🐛 Recorded video is stretched
### What were you trying to do?

Record video.

### Reproduceable Code

```tsx
<Camera
 ref={cameraRef}
 style={styles.recordVideo}
 device={devices.front}
 video={true}
 audio={true}
 isActive={isActiveRecordVideo}
 preset="iframe-1280x720"
/>


or Full code

import React, {useLayoutEffect, useRef, useState} from 'react';
import {
  Pressable,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import {VLCPlayer} from 'react-native-vlc-media-player';
import {Camera, useCameraDevices} from 'react-native-vision-camera';
import {RNCamera} from 'react-native-camera';


const AppVisionCamera = () => {
  const devices = useCameraDevices();

  const [isRecordingVide, setIsRecordingVide] = useState(false);
  const [recordedVideo, setRecordedVideo] = useState(null);

  const cameraRef = useRef();

  useLayoutEffect(() => {
    const getPermissions = async () => {
      const cameraPermission = await Camera.getCameraPermissionStatus();
      if (cameraPermission === 'not-determined') {
        const newCameraPermission = await Camera.requestCameraPermission();
        console.log('newCameraPermission', newCameraPermission);
      }
      const microphonePermission = await Camera.getMicrophonePermissionStatus();
      console.log('microphonePermission', microphonePermission);
      if (microphonePermission === 'not-determined') {
        const newMicrophonePermission =
          await Camera.requestMicrophonePermission();
        console.log('newMicrophonePermission', newMicrophonePermission);
      }
    };
    getPermissions();
  }, []);

  const onStartRecording = async () => {
    setRecordedVideo(null);
    setIsRecordingVide(true);
    console.log('cameraRef', cameraRef.current);
    cameraRef.current.startRecording({
      fileType: 'mp4',
      onRecordingFinished: async (video) => {
        console.log('onRecordingFinished', video);
        setRecordedVideo(video.path);
      },
      onRecordingError: (error) => {
        console.error('onRecordingError', error);
      },
    });
  };

  const onStopRecording = async () => {
    await cameraRef.current.stopRecording();
    setIsRecordingVide(false);
  };

  return (
    <SafeAreaView style={StyleSheet.absoluteFill}>
      <StatusBar barStyle="dark-content"/>
      <ScrollView contentInsetAdjustmentBehavior="automatic">
        
          <View style={styles.viewRecordVideo}>
            {devices.front && (
              <Camera
                ref={cameraRef}
                style={styles.recordVideo}
                device={devices.front}
                video={true}
                audio={true}
                isActive={true}
                preset="high"
              />
            )}
          </View>

        <View style={styles.viewButtons}>
          {isRecordingVide ? (
            <Pressable onPress={onStopRecording}>
              <Text style={styles.buttonText}>Stop record</Text>
            </Pressable>
          ) : (
            <Pressable onPress={onStartRecording}>
              <Text style={styles.buttonText}>Start record</Text>
            </Pressable>
          )}
        </View>

        <View style={styles.viewPlayer}>
          {recordedVideo && (
            <VLCPlayer
              style={styles.player}
              resizeMode="contain"
              repeat={true}
              source={{uri: recordedVideo}}
            />
          )}
        </View>
        <View style={styles.viewButtons}>
          <Pressable
            onPress={() => setRecordedVideo(null)}>
            <Text style={styles.buttonText}>Remove video</Text>
          </Pressable>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};


const styles = StyleSheet.create({
  viewPlayer: {
    width: '100%',
    height: 220,
  },
  player: {
    flex: 1,
  },

  viewRecordVideo: {
    width: '100%',
    height: 300,
  },
  recordVideo: {
    flex: 1,
  },

  viewButtons: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 50,
    backgroundColor: `black`
  },
  buttonText: {
    padding: 10,
    fontSize: 20,
    color: 'white',
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 8,
  },
});


export default AppVisionCamera;
```

### What happened instead?

When I playback recorded video with `preset="iframe-1280x720 or iframe-960x540"` I have stretched video.
You can see a bug on this [video](https://drive.google.com/file/d/1V9iGkFxD5ffzm7rKL0XGD55NeXhe2gVF/view)

### Relevant log output

_No response_

### Device

iPhone 7 (IOS 15.0)

### VisionCamera Version

2.8.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### LINKED ISSUE #2107: 🐛 Android video is dark & stretched on front camera
### What's happening?

The camera is very dark when using `react-native-vision-camera` when compared to the Android Camera (Front camera only)

# Front
Previous versions (Such as v2) do not have this dark of a front camera. I did notice when loading the app, the first frame is correctly bright, once it finishes loading it dims.
## Android Camera

# Back
Seems good enough (I assume some pre-processing is done with Android's camera making it _slightly_ brighter
## Android Camera 

Camera is also vertically stretched when using the front camera within `react-native-vision-camera`. (In addition to the zoom thats been existing even in v2)
(Challenging to get photos of this as the image is very dark, but let me know if you'd like some screenshots)

### Reproduceable Code

Latest Example app from `react-native-vision-camera` https://github.com/mrousavy/react-native-vision-camera/tree/main/package/example

### Relevant log output

No errors / warnings / logs were displayed.
Let me know if there is debug logging I can enable.

### Camera Device

```json
[
  {
    "formats": [
    ],
    "hardwareLevel": "full",
    "hasFlash": true,
    "hasTorch": true,
    "id": "0",
    "isMultiCam": false,
    "maxZoom": 4,
    "minZoom": 1,
    "name": "BACK (0)",
    "neutralZoom": 1,
    "physicalDevices": [
      "wide-angle-camera"
    ],
    "position": "back",
    "sensorOrientation": "landscape-right",
    "supportsFocus": true,
    "supportsLowLightBoost": false,
    "supportsRawCapture": true
  },
  {
    "formats": [
    ],
    "hardwareLevel": "full",
    "hasFlash": false,
    "hasTorch": false,
    "id": "1",
    "isMultiCam": false,
    "maxZoom": 4,
    "minZoom": 1,
    "name": "FRONT (1)",
    "neutralZoom": 1,
    "physicalDevices": [
      "wide-angle-camera"
    ],
    "position": "front",
    "sensorOrientation": "landscape-left",
    "supportsFocus": true,
    "supportsLowLightBoost": false,
    "supportsRawCapture": true
  }
]
```

### Device

Samsung Galaxy A03s (Android 13)

### VisionCamera Version

>=3.3.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### LINKED ISSUE #2142: 🐛 Camera stretched on Android
### What's happening?

Camera is stretched on Android, behavior is not consistent as sometimes when closing the navbar and reopening the stretch is gone.
image.

issue reproduced on these two devices:

-  Samsung Galaxy S9 SM G960F, Android version 8
-  OnePlus 5T, Android version 10

### Reproduceable Code

```tsx
const device = useCameraDevice('back');    
const format =  getCameraFormat(device, [
        { resizeTo: { width: camContainerPosition?.width ?? '', height: 
        camContainerPosition?.height ?? '' } },
        { photoResolution: 'max' },
        { videoResolution: 'max' },
        { autoFocusSystem: 'contrast-detection' },
        { videoStabilizationModes: ['on', 'on', 'cinematic-extended'] } 
    ]);
    const fps = format.maxFps >= 240 ? 240 : format.maxFps;
    const touchToFocus = async (event) => {
        if (!device.supportsFocus || !isCameraFocusReady.current) return;
        let point = {
            x: Math.round(event.pageX - camLocation.x),
            y: Math.round(event.pageY - camLocation.y)
        };
        try {
            isCameraFocusReady.current = false;
            await cameraRef?.current?.focus(point);
            setTimeout(() => {
                isCameraFocusReady.current = true;
            }, 200);
        } catch (error) {

        }
    };
 <Camera
   format={format}
   isActive={isAndroid ? !paused : true}
   photo={true}
   orientation={'portrait'}
   ref={cameraRef}
   enableHighQualityPhotos={true}
   fps={fps}
   preset='photo'
   enableZoomGesture={true}
   onLayout={handleCameraLayout}
   device={device}
   zoom={device.neutralZoom}
   style={{ flex: 1 }}
   onTouchEnd={(x) => touchToFocus(x.nativeEvent)}
   />
```

### Relevant log output

```shell
no logs
```

### Camera Device

```json
{"sensorOrientation":
"landscape-right",
"hardwareLevel": "full",
"maxZoom": 8,
"minZoom":1,
"supportsLowLightBoost":false,
"neutralZoom":1,
"physicalDevices":["wide-angle-camera"],
"supportsFocus":true,
"supportsRawCapture" true,
"isMultiCam":false,
"name":"BACK(0)",
"hasFlash" true,
"has Torch" true,
"position":"back",
"id":"0"}
```

### Device

OnePlus 5T, Android version 10

### VisionCamera Version

3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### LINKED ISSUE #2311: ❓ Preview stretched in my app but not in the example on same device
### Question

I don't understand why my camera preview is stretched in my Android app but not with your example on my tablet device...

### What I tried

I use the same CameraPage.tsx file in my app like in your example.
The format below props given to the camera component is the same in my app than in your example

{
   "format":{
      "autoFocusSystem":"contrast-detection",
      "fieldOfView":85.2381275912114,
      "maxFps":30,
      "maxISO":1600,
      "maxZoom":4,
      "minFps":1,
      "minISO":100,
      "photoHeight":1600,
      "photoWidth":2560,
      "pixelFormats":[
         "yuv",
         "native"
      ],
      "supportsDepthCapture":false,
      "supportsPhotoHdr":false,
      "supportsVideoHdr":false,
      "videoHeight":960,
      "videoStabilizationModes":[
         "off",
         "off"
      ],
      "videoWidth":1440
   }
}

### VisionCamera Version

3.6.17

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

### LINKED ISSUE #2380: 🐛 The camera's displayed image is flattened
### What's happening?

I wanted to take a photo. But when I open the camera, the **displayed image is flattened on android**.
I created a **project from scratch and the problem persists**. I tried on two different android devices. I don't tried on IOS.

**When I open the camera in the app, the image becomes flattened. If I do a hot reload or open another app with a camera and return to my app, the image returns to normal..**

I took two screenshot from app to show the error. First image is flattened and second image is normal after make a hot reload. _These images were not photos taken, they are just a screenshot of the app._

       |     

In device log the **sensorOrientation** is ** landscape-left**, but **I have it set to portrait orientation**

**dependencies**
`{ "react": "18.2.0", "react-native": "0.72.9", "react-native-vision-camera": "^3.7.0" }`

### Reproduceable Code

```tsx
const device = useCameraDevice('front');

<Camera
  style={StyleSheet.absoluteFill}
  photo={true}
  device={device}
  isActive={true}
  orientation="portrait"
/>
```

### Relevant log output

```shell
Android logcat

2024-01-11 13:03:07.756 23316-23316 PreviewView             com.testingvisioncamera              I  Creating PreviewView...
2024-01-11 13:03:07.756 23316-23316 PreviewView             com.testingvisioncamera              I  Content Size: 1920x1080 (0.5625) | Container Size: 0x0 (NaN)
2024-01-11 13:03:07.757 23316-23316 PreviewView             com.testingvisioncamera              I  PreviewView is 0x0, rendering 1920x1080 content. Resizing to: 0x0 (COVER)
2024-01-11 13:03:07.758 23316-23316 CameraView              com.testingvisioncamera              I  Updating CameraSession...
2024-01-11 13:03:07.764 23316-28160 CameraSession           com.testingvisioncamera              I  configure { ... }: Waiting for lock...
2024-01-11 13:03:07.766 23316-28160 CameraSession           com.testingvisioncamera              I  configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=true, outputsChanged=true, sidePropsChanged=true, isActiveChanged=true)
2024-01-11 13:03:07.766 23316-28160 CameraSession           com.testingvisioncamera              I  isActive is false, skipping CameraDevice configuration.
2024-01-11 13:03:07.766 23316-28160 CameraSession           com.testingvisioncamera              I  isActive is false, skipping CameraCaptureSession configuration.
2024-01-11 13:03:07.766 23316-28160 CameraSession           com.testingvisioncamera              I  Successfully updated CameraSession Configuration! isActive: false
2024-01-11 13:03:07.779 23316-23316 CameraView              com.testingvisioncamera              I  Updating CameraSession...
2024-01-11 13:03:07.779 23316-28160 CameraSession           com.testingvisioncamera              I  configure { ... }: Waiting for lock...
2024-01-11 13:03:07.779 23316-28160 CameraSession           com.testingvisioncamera              I  configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=true, outputsChanged=true, sidePropsChanged=true, isActiveChanged=true)
2024-01-11 13:03:07.780 23316-28160 CameraSession           com.testingvisioncamera              I  Need to rebuild CameraDevice and CameraCaptureSession...
2024-01-11 13:03:07.780 23316-23316 PreviewView             com.testingvisioncamera              I  Content Size: 1920x1080 (0.5625) | Container Size: 1080x2055 (0.5255474452554745)
2024-01-11 13:03:07.780 23316-23316 PreviewView             com.testingvisioncamera              I  PreviewView is 1080x2055, rendering 1920x1080 content. Resizing to: 1156x2055 (COVER)
2024-01-11 13:03:07.780 23316-28160 CameraSession           com.testingvisioncamera              I  Configuring Camera #1...
2024-01-11 13:03:07.783 23316-28160 CameraManager           com.testingvisioncamera              I  Camera #1: Opening...
2024-01-11 13:03:07.775 23316-23316 sionCamera.main         com.testingvisioncamera              W  type=1400 audit(0.0:25252): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=22306 scontext=u:r:untrusted_app:s0:c133,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2024-01-11 13:03:07.788 23316-28160 libc                    com.testingvisioncamera              E  Access denied finding property "persist.vendor.camera.privapp.list"
2024-01-11 13:03:07.794 23316-23316 CameraSession           com.testingvisioncamera              I  PreviewView Surface created! Surface(name=null)/@0x8724d4a
2024-01-11 13:03:07.794 23316-23316 CameraSession           com.testingvisioncamera              I  Setting Preview Output...
2024-01-11 13:03:07.794 23316-23316 CameraSession           com.testingvisioncamera              I  PreviewView Surface updated! Surface(name=null)/@0x8724d4a 1156 x 2055
2024-01-11 13:03:07.797 23316-28060 CameraDevices           com.testingvisioncamera              I  Camera #1 is now unavailable.
2024-01-11 13:03:07.829 23316-28160 CameraSession           com.testingvisioncamera              I  configure { ... }: Waiting for lock...
2024-01-11 13:03:07.830 23316-28160 CameraManager           com.testingvisioncamera              I  Camera #1: Opened!
2024-01-11 13:03:07.834 23316-28160 CameraSession           com.testingvisioncamera              I  Successfully configured Camera #1!
2024-01-11 13:03:07.834 23316-28160 CameraSession           com.testingvisioncamera              I  Destroying previous outputs...
2024-01-11 13:03:07.836 23316-28160 CameraSession           com.testingvisioncamera              I  Creating outputs for Camera #1...
2024-01-11 13:03:07.837 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Camera #1: Creating Capture Session #1... (Hardware Level: 3 | Outputs: [])
2024-01-11 13:03:07.838 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Using new API (>=28)
2024-01-11 13:03:07.843 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Camera #1: Successfully created CameraCaptureSession #1!
2024-01-11 13:03:07.843 23316-28160 CameraSession           com.testingvisioncamera              I  Successfully configured Session with 0 outputs for Camera #1!
2024-01-11 13:03:07.843 23316-28160 CameraSession           com.testingvisioncamera              I  CameraSession has no repeating outputs (Preview, Video, CodeScanner), skipping CaptureRequest...
2024-01-11 13:03:07.843 23316-28160 CameraSession           com.testingvisioncamera              I  Successfully updated CameraSession Configuration! isActive: true
2024-01-11 13:03:07.843 23316-28160 CameraView              com.testingvisioncamera              I  invokeOnInitialized()
2024-01-11 13:03:07.844 23316-28160 CameraSession           com.testingvisioncamera              I  configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=false, outputsChanged=true, sidePropsChanged=true, isActiveChanged=false)
2024-01-11 13:03:07.844 23316-28160 CameraSession           com.testingvisioncamera              I  Destroying previous outputs...
2024-01-11 13:03:07.846 23316-28160 CameraSession           com.testingvisioncamera              I  Creating outputs for Camera #1...
2024-01-11 13:03:07.849 23316-28160 CameraSession           com.testingvisioncamera              I  Adding 1440x1080 Preview Output...
2024-01-11 13:03:07.850 23316-23316 PreviewView             com.testingvisioncamera              I  Resizing PreviewView to 1440 x 1080...
2024-01-11 13:03:07.852 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Camera #1: Creating Capture Session #2... (Hardware Level: 3 | Outputs: [PREVIEW (1440 x 1080)])
2024-01-11 13:03:07.852 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Using new API (>=28)
2024-01-11 13:03:07.860 23316-23316 CameraSession           com.testingvisioncamera              I  PreviewView Surface updated! Surface(name=null)/@0x8724d4a 1440 x 1080
2024-01-11 13:03:07.861 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Camera #1: Successfully created CameraCaptureSession #2!
2024-01-11 13:03:07.861 23316-28160 CreateCaptureSession    com.testingvisioncamera              I  Camera #1: CameraCaptureSession #1 has been closed.
2024-01-11 13:03:07.861 23316-28160 CameraSession           com.testingvisioncamera              I  Camera Session android.hardware.camera2.impl.CameraCaptureSessionImpl@a104dd8 has been closed.
2024-01-11 13:03:07.861 23316-28160 CameraSession           com.testingvisioncamera              I  Successfully configured Session with 1 outputs for Camera #1!
2024-01-11 13:03:07.865 23316-28160 CameraView              com.testingvisioncamera              I  invokeOnStarted()
2024-01-11 13:03:07.866 23316-28160 CameraSession           com.testingvisioncamera              I  Successfully updated CameraSession Configuration! isActive: true
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "maxExposure": 12,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minExposure": -12,
  "name": "FRONT (1)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "front",
  "id": "1"
}
```

### Device

Oneplus A5010 (Android 10); Xiaomi Mi 9 Lite (Android 9)

### VisionCamera Version

3.7.0

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### Edit 1

I recorded my device's screen to show what is happen.

Steps on video: I open my app and the image is flattened, so I open other app that use camera, and when back to my app the image is normal.

Error that appears in the final video:
`Camera.onError(unknown/unknown): [unknown/unknown] CAMERA_IN_USE (4): connectHelper:1516: Higher-priority client using camera, ID "1" currently unavailable [unknown/unknown: [unknown/unknown] CAMERA_IN_USE (4): connectHelper:1516: Higher-priority client using camera, ID "1" currently unavailable]`

### PR DESCRIPTION
**Pull request by mrousavy**
## What

**HUGE thanks to the [GitHub sponsors](https://github.com/sponsors/mrousavy) who sponsored me to fix this bug!** 💖

Fixes the PreviewView being stretched by awaiting the `SurfaceHolder`'s size change before configuring the Camera session on Android.

This will delay the Camera session startup time by a bit (130ms on my Huawei P10 for first init, 20ms afterwards), so https://github.com/mrousavy/react-native-vision-camera/issues/2518 is becoming even more relevant now.

I am not sure if there is another way to do this, but it seems like we really need to wait for the Surface View to resize properly before configuring the Camera with it. Weird.

Also prevents the display from going to sleep while the Camera is active, as an addition to https://github.com/mrousavy/react-native-vision-camera/pull/2421

## Changes

- Waits for the SurfaceView's Surface to actually change in size before configuring the Camera (fixes preview stretching)
- Flips `getMaximumPreviewSize()` dimensions to reflect sensor natural orientation
- Prevents the display from going to sleep while Camera is active (addition to https://github.com/mrousavy/react-native-vision-camera/pull/2421)

## Related issues

- Fixes https://github.com/mrousavy/react-native-vision-camera/issues/2311
- Fixes https://github.com/mrousavy/react-native-vision-camera/issues/452
- Fixes https://github.com/mrousavy/react-native-vision-camera/issues/2107
- Fixes https://github.com/mrousavy/react-native-vision-camera/issues/2142
- Fixes https://github.com/mrousavy/react-native-vision-camera/issues/2311
- Fixes https://github.com/mrousavy/react-native-vision-camera/issues/2380

### CODE REVIEW

**Comment by e-vural** [comment]
@mrousavy Hi. Is this fix included in [3.9.0-beta.1](https://github.com/mrousavy/react-native-vision-camera/compare/v3.9.0-beta.0...v3.9.0-beta.1)? I installed beta version but this problem continue.

**Comment by mrousavy** [comment]
@e-vural no, it is no.

**Comment by e-vural** [comment]
> @e-vural no, it is no.
Ok thanks. You are really doing perfect job!

**Comment by mrousavy** [comment]
This is now included in [v3.9.0-beta.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v3.9.0-beta.2) 🚀

**Comment by e-vural** [comment]
Perfect! Tested and works fine. Thank you @mrousavy

**Comment by nonam4** [comment]
I'm testing it and preview is now stretched horizontally. It seems to be ok vertically.
I'm testing on an old Galaxy J5 device.

**Comment by luicfrr** [comment]
@mrousavy I'm testing it on an old Galaxy J5 but image preview is in landscape while device is in portrait mode making preview horizontally stretched. I'm using front camera

**Comment by hungtrieu07** [comment]
Hi, I have an error: The camera showing in my app are stretching and dark in horizontal mode. I'm using the tablet named Samsung Tab A9+. My app are developed with React Native, this is my ```package.json```:

```
{
  "name": "FaceDetectProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.22.3",
    "@react-native-camera-roll/camera-roll": "^7.5.0",
    "@react-native-community/hooks": "^3.0.0",
    "@react-navigation/bottom-tabs": "^6.5.18",
    "@react-navigation/drawer": "^6.6.13",
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/native-stack": "^6.9.23",
    "@reduxjs/toolkit": "^2.2.1",
    "@types/react-native-vector-icons": "^6.4.18",
    "axios": "^1.6.8",
    "iconsax-react-native": "^0.0.8",
    "moment": "^2.30.1",
    "query-string": "^9.0.0",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-date-picker": "^4.4.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-image-crop-picker": "^0.40.3",
    "react-native-image-size": "^1.1.6",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-photo-manipulator": "^1.2.9",
    "react-native-reanimated": "^3.8.0",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-svg": "^15.1.0",
    "react-native-toast-message": "^2.2.0",
    "react-native-vector-icons": "^10.0.3",
    "react-native-vision-camera": "^3.9.1",
    "react-native-vision-camera-face-detector": "^1.3.5",
    "react-native-worklets-core": "^0.4.0",
    "react-navigation": "^5.0.0",
    "react-redux": "^9.1.0",
    "redux": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

**Pull request merged**
