### PR TITLE
🐛 fix: CLANG_CXX_LANGUAGE_STANDARD was in the wrong place

### LINKED ISSUE #1287: CLANG_CXX_LANGUAGE_STANDARD mismatch for iOS podspecs
### What were you trying to do?

package.json dependencies:
```
    "react-native": "0.70.3",
    "react-native-reanimated": "^2.11.0",
    "react-native-vision-camera": "^2.14.1"
```

empty project initialization fails on: `pod install`

### Reproduceable Code

```tsx
N/A
```

### What happened instead?

Pods installation fails.

Quite obviously, **VisionCamera.podspec.json** have:
```json
{
  "xcconfig": {
    "CLANG_CXX_LANGUAGE_STANDARD": "c++14",
    "HEADER_SEARCH_PATHS": "\"$(PODS_ROOT)/boost\" \"$(PODS_ROOT)/boost-for-react-native\" \"$(PODS_ROOT)/glog\" \"$(PODS_ROOT)/RCT-Folly\" \"${PODS_ROOT}/Headers/Public/React-hermes\" \"${PODS_ROOT}/Headers/Public/hermes-engine\"",
    "OTHER_CFLAGS": "$(inherited) -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DRNVERSION=70"
  }
}
```

While **hermes-engine.podspec.json** have:
```json
{
  "xcconfig": {
    "CLANG_CXX_LANGUAGE_STANDARD": "c++17",
    "CLANG_CXX_LIBRARY": "compiler-default",
    "GCC_PREPROCESSOR_DEFINITIONS": "HERMES_ENABLE_DEBUGGER=1"
  }
}
```

### Relevant log output

```shell
[!] Can't merge user_target_xcconfig for pod targets: ["VisionCamera", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.
```

### Device

N/A

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by CoryWritesCode**
## What

When running `pod install` I would still get this error, even after #1309 
image

## Changes

I just moved the code up a few lines to the correct place so `pod install` works correctly
image

## Tested on

iPhone 14 Pro (Sim)
iPhone SE 3rd gen (Sim)

## Related issues

closes #1287

### CODE REVIEW

**Comment by CoryWritesCode** [comment]
@mrousavy in case this has slipped past your notifications.

**Comment by mrousavy** [comment]
Hey! Oh sorry, it did slip past my notifications.

Hmm, are you sure that value belongs to the pod config, not in the xcconfig?

**Comment by CoryWritesCode** [comment]
@mrousavy tgis is where I've seen it in most other libraries and when I moved it here and build the app example it didn't show any warnings.

**Comment by markrickert** [comment]
I was running into this same issue and creating a patch with this change fixed it for me. I was upgrading an app from react native 0.67.5 to 0.68.6 when I ran into this build error.

**Comment by maskowe** [comment]
> I was running into this same issue and creating a patch with this change fixed it for me. I was upgrading an app from react native 0.67.5 to 0.68.6 when I ran into this build error.

@markrickert Could you please tell me which vision camera version you applied this patch to?  For ios, I'm using version 2.14.1 and can't upgrade higher due to other problems. ?

**Comment by markrickert** [comment]
> Could you please tell me which vision camera version you applied this patch to? For ios, I'm using version 2.14.1 and can't upgrade higher due to other problems. ?

@maskowe I've got this patch applied to `react-native-vision-camera@2.15.4` on `react-native@0.68.8`. Worked like a charm. When upgrading from 0.67->0.68, the xcode compiler changed to `c++17` for the new architecture so this change was required in my project to properly compile this library.

**Comment by maskowe** [comment]
Thanks

**Comment by mkdesilva** [comment]
I am encountering this same warning on react-native 0.66.5 and react-native-vision-camera 2.15.4. 

The changes in this PR fix it for me.

**Comment by eisodev** [comment]
Is this ever gonna be merged to a release?

Thanks.

**Comment by teodorszeltins** [comment]
Bump.

I hope this can soon be merged and released.

**Comment by mrousavy** [comment]
Hey! Is this still relevant for V3? If yes can you rebase so we can merge? If no, let's close this

**Comment by CoryWritesCode** [comment]
Yeah good call @mrousavy i don't know if it's relevant for v3 as I moved on to a different lib a little while after opening this PR. If anyone else still sees it on V3 you can use this Pr as a template!

**Pull request closed without merging**
