### PR TITLE
feat: Optionally compile out Location APIs

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Adds an option to compile-out any location privacy-sensitive APIs if you are not using them.

Simply set `$VCEnableLocation=false` to set the flag, and all CLLocationManager APIs will be removed.

This is useful to get past app review when you are not including the location tag in your Info.plist

Also, the `enableFrameProcessors` (and new `enableLocation`) flags in the expo config plugin now work!

## Related issues

- Closes https://github.com/mrousavy/react-native-vision-camera/pull/2719

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
Hi Marc,

I get this error while building on Xcode 15.2:

Screenshot 2024-04-19 at 19 01 05


edit, Podfile:

```ruby
    $VCEnableFrameProcessors = false
    $VCEnableLocation = false
```

edit 2: 
this fixes it: 

```c
  @objc
  final func requestLocationPermission(_ resolve: @escaping RCTPromiseResolveBlock, reject : @escaping RCTPromiseRejectBlock) {
    #if VISION_CAMERA_ENABLE_LOCATION
      CLLocationManager.requestAccess(for: .whenInUse) { status in
        resolve(status.descriptor)
      }
    #else
      let promise = Promise(resolver: resolve, rejecter: reject)
      promise.reject(error: .system(.locationNotEnabled))
    #endif
}
```

**Comment by mrousavy** [comment]
whoops yea just pushed a fix.

**Comment by giga123Z** [comment]
@mrousavy i use expo sdk version 50, how to set $VCEnableLocation=false when i use expo build development. Please help me!

**Comment by mrousavy** [comment]
before writing "please help me", read the docs.
It's in the Location docs.

**Comment by giga123Z** [comment]
@mrousavy  thank you, i just see 
image
https://react-native-vision-camera.com/docs/guides/location
Comment here for somebody same me!

**Pull request merged**
