### PR TITLE
fix: Apply orientation to video output

### PR DESCRIPTION
**Pull request by jkaufman**
## What
This PR updates video recording on Android to respect the orientation prop.

## Changes

- Call `startRecording` with `orientation` from `cameraView`.
- Apply a rotation derived from the orientation to the video output via `setTargetRotation`.

## Tested on
- Pixel 3a, Android 12
- Moto Stylus 5G (2022), Android 12

### CODE REVIEW

**Comment by jkaufman** [comment]
KTLint is passing locally after the whitespace addition to [CameraView.kt](https://github.com/mrousavy/react-native-vision-camera/pull/2912/commits/33cb67253f27618ee27670fa9afffa5d12846a80#diff-20630faec056f24cf68499c401620da9affc9e0c28d5c0c7837a96f17ec6f15c)

**Comment by tomtargosz** [comment]
Thanks for this PR, currently running into the same issue! I tested your branch locally and setting `orientation` to `"portrait"` or `"portrait-upside-down"` works as expected, but `"landscape-left"` and `"landscape-right"` look to be reversed. Holding my devices in landscape right orientation and then taking the video with `orientation="landscape-right"` results in the video being upside down. Same if I hold my phone in the opposite direction with `orientation="landscape-left"` . Aside from that working great!

Devices I tested with:
Pixel 3a XL on Android 11
Pixel 4 on Android 13
Pixel 7 on Android 14

**Comment by jkaufman** [comment]
@tomtargosz Yes, but that's [tracked elsewhere](https://github.com/mrousavy/react-native-vision-camera/issues/2802#issue-2263924578) with a [proposed PR](https://github.com/mrousavy/react-native-vision-camera/pull/2907) in review.

**Comment by tomtargosz** [comment]
Gotcha, thanks for the link! I think these 2 PRs in combination would be a great addition to the library.

**Comment by mrousavy** [comment]
Very nice, thank you so much. Full Orientation support is still a long way to go, but this is a good temporary solution.
LGTM!

**Pull request merged**
