### PR TITLE
feat: Silent and Vibrate mode, shutter sound is mute

### PR DESCRIPTION
**Pull request by quannq-vvt**
## What
when this PR appears: https://github.com/mrousavy/react-native-vision-camera/pull/1702 then android when taking a snap with silent mode and vibrate mode always has sound, this makes the app like an error on Android

## Tested on
Zflip 5
Samsung a54

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey - thanks for this PR mate, what happens **without** your change though? Does the app crash? What error is being thrown?

**Comment by quannq-vvt** [comment]
> Hey - thanks for this PR mate, what happens **without** your change though? Does the app crash? What error is being thrown?

It does not crash or throw an error, it's normal except if the user uses Android with silent or vibrate mode, it always has a shutter sound. It's so uncomfortable if your phone is silent but still makes a sound

**Comment by mrousavy** [comment]
Ah, I see! Okay well this is more of a "how do we want it to behave question"...

**Comment by quannq-vvt** [comment]
if you find it reasonable, hope you update soon! Thanks for your job

**Comment by omerts** [comment]
Hi, would like to see this merged as well please. We got a complient about this, since if the phone is in silent mode camera should not make sounds (especially since it makes the shutter sound by default).

**Comment by mrousavy** [comment]
I just fixed this in V4 and released it in the latest beta. Thanks @quannq-vvt, I took your approach and adjusted it a bit, but the idea is the same!

**Comment by quannq-vvt** [comment]
done

**Pull request closed without merging**
