### PR TITLE
feat: Monorepo support

### LINKED ISSUE #702: A problem occurred evaluating project ':react-native-vision-camera'🐛
### What were you trying to do?

I was running my app without issue with the version 2.10.0, but since the update of 2.11.0 the build failed with an exception.

on the /react-native-vision-camera/android/build.gradle' line: 8
it's looking for the file /react-native-vision-camera/node_modules/react-native/ReactAndroid/gradle.properties 
which doesn't exist (No such file or directory).

I tried to clean the caches but still happening
Screen Shot 2022-01-03 at 10 48 22

### Reproduceable Code

```tsx
"react-native-vision-camera": "^2.11.0",
```

### What happened instead?

FAILURE: Build failed with an exception.

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yohanbalassiano/Sites/Deelt/app/deelt/node_modules/react-native-vision-camera/android/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera'.
> /Users/yohanbalassiano/Sites/Deelt/app/deelt/node_modules/react-native-vision-camera/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
```

### Device

OnePlus Nord

### VisionCamera Version

2.11.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Finds `node_modules/` path dynamically.

## Related issues

* Fixes #702

### CODE REVIEW

**Comment by mrousavy** [comment]
cc @Hirbod

**Comment by hirbod** [comment]
@mrousavy not working for me:

```
> Configure project :react-native-vision-camera
VisionCamera: node_modules/ found at: /path/to/my/app/node_modules/react-native-vision-camera/node_modules

FAILURE: Build failed with an exception.

* Where:
Build file '/path/to/my/app/node_modules/react-native-vision-camera/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera'.
> /path/to/my/app/node_modules/react-native-vision-camera/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
```

**Comment by hirbod** [comment]
I think the last `node_modules` is redundant.

**Comment by mrousavy** [comment]
Does `node_modules/react-native-vision-camera` contain another `node_modules/` folder in your case..?

**Comment by hirbod** [comment]
Yes.
Bildschirmfoto 2022-01-03 um 12 19 59

**Comment by mrousavy** [comment]
Well delete it

**Comment by mrousavy** [comment]
That shouldn't be there, can you tell me which command created that folder?

**Comment by hirbod** [comment]
But where is it coming from?

**Comment by hirbod** [comment]
@mrousavy I am not sure. Removing the folder fixed that. My gut tells me that `patch-package` might create it. I will make a test.

**Comment by hirbod** [comment]
@mrousavy I can't reproduce WHAT command created that folder but I can confirm that my monorepo setup is working FLAWLESSLY now :).

We're getting there my man! Thanks a ton for your effort. Coffees incoming!

**Pull request merged**
