### PR TITLE
fix: RN 0.73 support by solving #2263: Kotlin compilation fails due to "'hasConstants' overrides nothing" at CameraDevicesManager.kt

### PR DESCRIPTION
**Pull request by parlet**
fix: RN 0.73 support by solving #2263: Kotlin compilation fails due to "'hasConstants' overrides nothing" at CameraDevicesManager.kt

### CODE REVIEW

**Comment by 4cc3ssX** [comment]
LGTM!

Tested on **Redmi Note 11T 5G**

- Android Version 13 (MIUI 14)

**Comment by luas10c** [comment]
<@mrousavy> this fixes a problem.

**Review by idrissakhi — APPROVED** [review]

**Comment by mrousavy** [comment]
Hey - can you please test if this still works in RN 0.72/0.71?

I remember that there could be warnings in the console if you don't override this...

**Review by rivaslive — APPROVED** [review]

**Comment by rivaslive** [comment]
Please you could merge this change? I working in react 0.73.0 @mrousavy

**Comment by parlet** [comment]
> Hey - can you please test if this still works in RN 0.72/0.71?
> 
> I remember that there could be warnings in the console if you don't override this...

Hey @mrousavy, 👋

Thank you for reviewing this!

I made sure to check for backward compatibility with RN 0.72.7 before raising the PR, and I didn't encounter any problems or build time warnings.

**Comment by mrousavy** [comment]
Awesome, thanks for testing man - LGTM!

**Pull request merged**
