### PR TITLE
fix: Fix RecordingSession nil crash by keeping it local

### LINKED ISSUE #936: 🐛 [ios] Crashing on fast start / stopRecording calls - Unexpectedly found nil while unwrapping an Optional value
### What were you trying to do?

When I try to create couple of short video shots (<1s) with a more rapid "tapping" approach, older devices hick up and crash.
It does not happen on powerful iOS devices (such as iPhone 12 Pro Max / 13 Pro Max), but iPhone 7 and SE tend to crash quite frequently, even if I wait a bit more before i hit the button

### Reproduceable Code

```tsx
Just called startRecord / stopRecording quite frequently. Will happen at some point (sometimes after the 5th try, sometimes after the 15th hit).
```

### What happened instead?

The app crashes with `Thread 40: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

Bildschirmfoto 2022-03-25 um 21 21 06
`

### Relevant log output

```shell
The app crashes with `Thread 40: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

### Device

iPhone 7 (iOS 12.3.1)

### VisionCamera Version

2.13.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
Fixes #936

### CODE REVIEW

**Comment by hirbod** [comment]
@mrousavy is this one here a draft or ready? I could test it if you like.

**Comment by mrousavy** [comment]
@hirbod please test. I am not sure if this is the best solution here

**Comment by hirbod** [comment]
@mrousavy I tried, but it fails with "Cannot find error in scope.

Bildschirmfoto 2022-04-14 um 11 17 09

**Comment by mrousavy** [comment]
fixed with https://github.com/mrousavy/react-native-vision-camera/pull/938/commits/7ecd19b5f1dad0a42cb0bb3fcc9146da46f71f7e

**Comment by hirbod** [comment]
@mrousavy after applying your fix, I could not reproduce the crash anymore. The only thing that keeps crashing now when spamming start/stop is

`-[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 1` (#930)

From my end, this specific issue seems to be fixed.

**Pull request merged**
