### PR TITLE
feat: Add customizable Video Bit Rate (`videoBitRate`) 

### LINKED ISSUE #788: ✨ Output Bitrate Modification
### What feature or enhancement are you suggesting?

In react-native-camera we had the ability to change the video bitrate. This is particularly useful if you're using the component to send the video up to a server on a poor connection. 

See attached documentation for how it worked there(videoBitrate prop):
https://react-native-camera.github.io/react-native-camera/docs/api#method-type-1

Places in their code this was able to be modified:
https://github.com/react-native-camera/react-native-camera/blob/v4.2.1/ios/RN/RNCamera.m#L1207-L1215
https://github.com/react-native-camera/react-native-camera/blob/v4.2.1/android/src/main/java/com/google/android/cameraview/Camera2.java#L1422

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

You could do post processing on the device using FFMpeg but that seems like a poor idea if you can modify the bitrate during recording.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

### LINKED ISSUE #1548: How to reduce the size of recorded videos on android ❓
### Question

How to reduce the size of videos recorded on android ?, Currently a video of about 8 seconds has approximately 20Mb, even using different presets the size remains exaggeratedly large

### What I tried

I tried setting preset='vga-640x480',
and another presets

I also tried to define videoCodec inside the RecordVideoOptions property, but even so the size is exaggeratedly large

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Implements customizing the bit-rate for video recordings by adding a `videoBitRate` property to `startRecording(..)` options.

API:

```ts
videoBitRate?: 'low' | 'normal' | 'high' | number // Mbps
```

Examples:

```ts
camera.current.startRecording({
  ...props,
  videoBitRate: 'low' // 0.8x
})
```

```ts
camera.current.startRecording({
  ...props,
  videoBitRate: 'high' // 1.2x
})
```

```ts
camera.current.startRecording({
  ...props,
  videoBitRate: 10 // Mbps
})
```

## Related issues

- Closes https://github.com/mrousavy/react-native-vision-camera/issues/788
- Closes #1548

### CODE REVIEW

**Comment by favaztechcurve** [comment]
@mrousavy  for a video which have 4 -5 min recording iam geting the video size as 545 MB. 


The code i have given while starting recording.

   "react-native-vision-camera": "^3.8.0",

 camera.current.startRecording({
          videoBitrate: 0.5,
          video: {
            codec: 'h265',
            frameRate: 30,
          },
          onRecordingFinished: video => {
            setVideoPath(video.path);
          },
          onRecordingError: error => console.error(error),
        });

**Comment by favaztechcurve** [comment]
> @mrousavy for a video which have 4 -5 min recording iam geting the video size as 545 MB.
> 
> The code i have given while starting recording.
> 
> "react-native-vision-camera": "^3.8.0",
> 
> camera.current.startRecording({ videoBitrate: 0.5, video: { codec: 'h265', frameRate: 30, }, onRecordingFinished: video => { setVideoPath(video.path); }, onRecordingError: error => console.error(error), });

@mrousavy  is this issue only for me ? i tried all your way to reduce the video size but no luck. please help me to reduce this app size on android

**Comment by mrousavy** [comment]
1. Please stop pinging me.
2. You didn't add any information about your device, OS, logs - I don't even know if you're seeing this on Android or iOS. Can't help you.
3. Did you read [the **Video Bit-Rate** docs](https://react-native-vision-camera.com/docs/guides/recording-videos#video-bit-rate)? `0.5` is not a valid value for bit rate.

**Comment by vishalyad16** [comment]
@mrousavy 
 I am using 
"react-native-vision-camera": "^4.4.2",
"react-native": "^0.73.8",

 const format = useCameraFormat(backCamera, [
        { videoResolution: { width: 1280, height: 720 } },
        { fps: 30 },{pixelFormat: 'native'}
        ])

await cameraRef.current?.startRecording({
                    videoCodec: 'h264',
                    videoBitRate: 'extra-low',
                    onRecordingFinished: video => {
                        const path = video?.path
                        setVideoPath(path)
                        clearInterval(timerId);
                        setCustomUrl(path)
                    },
                    onRecordingError: error => {
                        setIsRecording(false);
                        console.error('Recording error: ', error);
                        clearInterval(timerId);
                    }
                });
     While recording a video for 1 minute, the file size becomes as large as 151 MB. How can I reduce the file size? Please help.

**Comment by brianw-tech** [comment]
> @mrousavy I am using "react-native-vision-camera": "^4.4.2", "react-native": "^0.73.8",
> 
> const format = useCameraFormat(backCamera, [ { videoResolution: { width: 1280, height: 720 } }, { fps: 30 },{pixelFormat: 'native'} ])
> 
> await cameraRef.current?.startRecording({ videoCodec: 'h264', videoBitRate: 'extra-low', onRecordingFinished: video => { const path = video?.path setVideoPath(path) clearInterval(timerId); setCustomUrl(path) }, onRecordingError: error => { setIsRecording(false); console.error('Recording error: ', error); clearInterval(timerId); } }); While recording a video for 1 minute, the file size becomes as large as 151 MB. How can I reduce the file size? Please help.

did you get a solution?

**Pull request merged**
