### PR TITLE
Close camera session in onDetachedFromWindow

### PR DESCRIPTION
**Pull request by vahidid**

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey, thanks for your PR. There seems to be unrelated changes here, please revert the changes for those 2 files.

**Comment by vahidid** [comment]
Yes, Those files belongs to Jetbrains Fleet :))
I deleted them.

**Comment by mrousavy** [comment]
Hey actually I am not sure if this does anything differently.

Right now the flow was like this:

1. In `onDetachedFromWindow()`, we call `updateLifecycle()`: https://github.com/mrousavy/react-native-vision-camera/blob/02726d47f781d4568ea2a6a9478d7348d4bc3565/package/android/src/main/java/com/mrousavy/camera/CameraView.kt#L129
2. In `updateLifecycle()`, we will call `setActive(false)`: https://github.com/mrousavy/react-native-vision-camera/blob/02726d47f781d4568ea2a6a9478d7348d4bc3565/package/android/src/main/java/com/mrousavy/camera/CameraView.kt#L252
3. In `setActive(false)`, we will call `stopRunning()`: https://github.com/mrousavy/react-native-vision-camera/blob/02726d47f781d4568ea2a6a9478d7348d4bc3565/package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt#L211
4. In `stopRunning()`, we will call `destroy()`: https://github.com/mrousavy/react-native-vision-camera/blob/02726d47f781d4568ea2a6a9478d7348d4bc3565/package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt#L576
5. And in `destroy()`, we close everything: https://github.com/mrousavy/react-native-vision-camera/blob/02726d47f781d4568ea2a6a9478d7348d4bc3565/package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt#L483-L493

So effectively your PR does not change anything in here as far as I can see, except that it also calls `close()` on `outputs` and photosynchronizer: https://github.com/mrousavy/react-native-vision-camera/blob/02726d47f781d4568ea2a6a9478d7348d4bc3565/package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt#L115-L122

Did you have any crashes before without your PR? What was the reason for your PR? @vahidid

**Comment by vahidid** [comment]
Yes i had and i explain it in [here](https://github.com/mrousavy/react-native-vision-camera/issues/1958#issue-1933687203).
I had crashes on some android device like Xiaomi Note 11 pro plus but on my phone (Xiaomi 11 pro) it was working.

**Comment by mrousavy** [comment]
Maybe this fixes your issue? https://github.com/mrousavy/react-native-vision-camera/pull/1972

**Pull request merged**
