### PR TITLE
fix: Fix image rotated when flipped in Android

### LINKED ISSUE #146: 🐛 Selfie on Android Pixel 2 XL (OS version 11) is rotated
## What
Platform: Android
Tested OS version: Android 11
Devices tested: Pixel 2 XL and Pixel 3a
library version: 1.0.11

I notice using both my app and your example is that Selfie images are rotated 90 degrees counterclockwise. I checked the metadata on my app and I can see Orientation is 0 (I believe this is 0 degrees?).

at the moment I cannot move up to 2.0 as reanimaed 2,0 has debugging issues due to TurboModules.

## Reproducable sample

1. Open the example app
2. switch to selfie camera
3. capture an image

The preview of the captured image appears rotated 90 degrees counter clockwise

## Environment

* Platform(s):
  * [ ] iOS
  * [ X] Android
* react-native version: __0.64_
* react-native-vision-camera version: _1.0.11__
* react-native-reanimated version: N/A

### PR DESCRIPTION
**Pull request by didithilmy**
## What

This PR fixes a bug that causes image to rotate when using a front camera in Android.

## Changes
This PR changes the `flipImage` method in ImageProxy.save.kt to fix the image rotation based on Exif `Orientation` value.

## Tested on

Pixel 5, Android 11

## Related issues
Fixes #146

### CODE REVIEW

**Comment by mrousavy** [comment]
Hi, thanks for your PR!

Will test the change asap - looking at the code, do you think there's a possibility for this being a one-liner by applying the EXIF Transform value directly to the Matrix somehow?

**Comment by didithilmy** [comment]
You're very welcome!

I'm not sure I fully get what you mean 🤔 Do you mean can we try to flip the image by simply setting the Exif metadata value?

If so, I think so.. but I've been trying it with no luck. In theory, we could use `ExifInterface` to set the `Orientation` attributes and save it, but somehow it did not work.

I was trying something like this:
```kotlin
fun flipImage2(file: File) {
  val exif = ExifInterface(file.absolutePath)
  val orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_UNDEFINED)

  when (orientation) {
    ExifInterface.ORIENTATION_UNDEFINED -> {
      exif.setAttribute(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_FLIP_HORIZONTAL.toString())
    }
    ExifInterface.ORIENTATION_NORMAL -> {
      exif.setAttribute(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_FLIP_HORIZONTAL.toString())
    }
    ExifInterface.ORIENTATION_ROTATE_180 -> {
      exif.setAttribute(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_FLIP_VERTICAL.toString())
    }
    ExifInterface.ORIENTATION_ROTATE_90 -> {
      exif.setAttribute(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_TRANSPOSE.toString())
    }
    ExifInterface.ORIENTATION_ROTATE_270 -> {
      exif.setAttribute(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_TRANSVERSE.toString())
    }
  }

  exif.saveAttributes()
}
```

```kotlin
fun ImageProxy.save(file: File, flipHorizontally: Boolean) {
  when (format) {
    ImageFormat.JPEG -> {
      if (flipHorizontally) {
        flipImage2(file)
      }

      val buffer = planes[0].buffer
      var bytes = ByteArray(buffer.remaining())

      // copy image from buffer to byte array
      buffer.get(bytes)

      val output = FileOutputStream(file)
      output.write(bytes)
      output.close()
    }
// ...
```

**Comment by mrousavy** [comment]
Ah yeah no I'd like to avoid that since both of those are reading & writing from the file. Ideally I want it to be fast, so in-memory.

**Comment by madeeha96** [comment]
@mrousavy can you confirm when will this PR be merged?

**Comment by mrousavy** [comment]
@madeeha96 I'd have to test first if the behaviour is now consistent on iOS and Android. Also, I have to make sure this doesn't introduce any regressions, neither bugs or performance.
It would help if people helped me test this on various different devices :)

**Comment by madeeha96** [comment]
> fix: Fix image rotated when flipped in Android
Tested on Samsung note 10 lite, iphone 7 and iphone 12.

**Comment by mrousavy** [comment]
Thank you for the PR! LGTM

**Comment by rodgomescrn** [comment]
huge kudos for you @didithilmy I was trying to figure out this for a long time

**Pull request merged**
