### PR TITLE
feat: Make Reanimated optional (disable Frame Processors if REA v2 is not installed)

### LINKED ISSUE #411: ❓ Is react-native-reanimated now required?
### Question

Is react-native-reanimated now required?

### What I tried

In 2.4.1, I could build my iOS and Android app without having react-native-reanimated installed.

However, when I upgraded to 2.7.0 just now, both my iOS and Android builds failed due to a) a missing RNReanimated header for iOS, and b) a missing ":react-native-reanimated" project for Android.

According to the docs, the Reanimated library is only needed for frame processors, so I thought it was optional. 😢

EDIT: In fact, it seems like 2.5.0 is the first version that causes this build error. FYI I'm still running RN 0.64.1

EDIT2: I tried disabling frame processors in iOS by adding `"VISION_CAMERA_DISABLE_FRAME_PROCESSORS=1",` to my project.pbxproj, but the build error persists. (Not sure how to disable frame processors in Android...)

### VisionCamera Version

2.7.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

### LINKED ISSUE #660: 🐛 Documentation doesn't mention that Reanimated v2 is required
### What were you trying to do?

[Getting Started guide](https://mrousavy.com/react-native-vision-camera/docs/guides) hints that Reanimated v2 would only be required when Frame Processors are used. However, Reanimated v2 seems to be always required even if Frame Processors have been disabled.

image

### What happened instead?

When building the app on iOS without Reanimated v2, the building process fails with the error:

> 'RNReanimated/Scheduler.h' file not found

By looking at the issues & PRs, it seems like the Reanimated v2 is always required:  https://github.com/mrousavy/react-native-vision-camera/issues/411  https://github.com/mrousavy/react-native-vision-camera/pull/412

If that's the case, it would be great if the Getting Started page and the Troubleshoot page mentioned this.

### Device

iOS, Android

### VisionCamera Version

2.1.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
## What

This PR adds support for using VisionCamera without Reanimated v2. A lot of people didn't migrate to v2 yet, but they should also be able to use VisionCamera - they just can't use Frame Processors.

Implemented:

* [x] iOS
* [ ] Android

## Blockers

I don't really know how to make a dependency/library optional in CMake/build.gradle....

## Related issues

* Fixes https://github.com/mrousavy/react-native-vision-camera/issues/411
* Fixes #660

### CODE REVIEW

**Comment by jzxchiang1** [comment]
This is awesome!

Is anything here relevant: https://docs.gradle.org/current/userguide/feature_variants.html?

**Comment by jzxchiang1** [comment]
Any luck with this?

**Comment by mrousavy** [comment]
Not yet, don't understand Gradle well enough yet.

**Comment by jzxchiang1** [comment]
Thanks for the update. I'll take a look as well.

**Comment by mrousavy** [comment]
@jzxchiang1 did you find anything? I need two things:

1. Make this optional: https://github.com/mrousavy/react-native-vision-camera/blob/8d24e344c9252a6a500e5f63a39539e0ff24fa11/android/build.gradle#L212
    when not found, set a variable in the `build.gradle` (e.g. `REANIMATED_AVAILABLE = false`), and then optionally remove the Java code. This seems problematic to me, because the Java code actually contains an Import from `com.swmansion.reanimated.xxx`.
2. Make this optional: https://github.com/mrousavy/react-native-vision-camera/blob/8d24e344c9252a6a500e5f63a39539e0ff24fa11/android/build.gradle#L228
    when not found, set a variable in the `build.gradle` (e.g. `REANIMATED_AVAILABLE = false`) which I can then pass to `externalNativeBuild` (to be read and used in `CMakeLists.txt`)

Any help appreciated. I can take it from there.

**Comment by mrousavy** [comment]
This _might_ be helpful: https://stackoverflow.com/a/16823279

**Comment by jzxchiang1** [comment]
The good news is that react-native-reanimated will actually support v8 quite soon. I just got it working after a lot of help from the maintainer of react-native-v8, who was awesome enough to share a couple of patches.

So I think this might not be urgent anymore, now that react-native-reanimated should support JSC, Hermes, and v8.

**Comment by angelos3lex** [comment]
@mrousavy Just in case we can't yet update to reanimated-v2 (in our case because we are using `react-native-draggable-flatlist` which is not yet compatible with v2 (https://github.com/computerjazz/react-native-draggable-flatlist/pull/335)), and we need the `react-native-vision-camera` but without frame-processors, Is there any workaround?

**Comment by mrousavy** [comment]
the workaround is to delete all of the C++ files and CMake setup 😅

**Comment by angelos3lex** [comment]
Do you think that making frame processors a separate repo from the vision camera and have it as an add-on (which would entirely need animated-V2), would be a solution?

**Comment by mrousavy** [comment]
No, because that is way more complex than simply allowing Frame Processors to be disabled if REA is not installed

**Comment by nelsonprsousa** [comment]
> @mrousavy Just in case we can't yet update to reanimated-v2 (in our case because we are using `react-native-draggable-flatlist` which is not yet compatible with v2 ([computerjazz/react-native-draggable-flatlist#335](https://github.com/computerjazz/react-native-draggable-flatlist/pull/335))), and we need the `react-native-vision-camera` but without frame-processors, Is there any workaround?

I believe react-native-draggable-flatlist is compatible with REA v2. It just doesn't uses the new REA v2 API, but the old one still works with V2.

@computerjazz knows better

**Comment by computerjazz** [comment]
@nelsonprsousa yep that's correct. react-native-draggable-flatlist uses the v1 api because performance is better with v1 when rendering an arbitrarily-long list where each item has complex animated value interactions (largely thanks to the `proc` node). This is only an implementation detail, the package works just fine with reanimated 2, and I actually have reanimated 2 as a peer dep just to allow me to transition to the new api whenever the perf issues are fixed.

Would love to get your take on this @mrousavy but I won't hijack this thread :). I know some performance fixes have landed in reanimated recently but last I checked the v2 api still resulted in low fps.

**Comment by mrousavy** [comment]
@jzxchiang1 can you test if it works for you now?

**Comment by mrousavy** [comment]
It works! Just tested both on Android and iOS, Reanimated is no longer required! And if you don't use Frame Processors, compile time is faster! :)

**Comment by jzxchiang1** [comment]
Sorry just saw this. Thank you! I ended up getting reanimated to work either way, but this is helpful as well.

**Pull request merged**
