### PR TITLE
Use ViewGroupManager instead of SimpleViewManager

### PR DESCRIPTION
**Pull request by NilsKrause**
## What

* This PR adds support for ListViews as child components of the Camera component.

## Changes

* This PR just changes the `SimpleViewManager` used in `android/src/main/java/com/mrousavy/camera/CameraViewManager.kt` to `ViewGroupManager`.

## Tested on

* Pixel 4a, Android 12

## Related issues

* None that I know of

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey, thank you for your PR!

Why would you want to add children to the Camera component though?

**Comment by NilsKrause** [comment]
I personally have no direct use case for it at the moment, but I was experimenting a bit with the component and saw that the component accepts children - but it just crashed when I added a FlatList. So I thought, when children are supported it would only make sense to also allow Lists.

**Comment by Angelk90** [comment]
@NilsKrause : What android device did you try on?

**Comment by NilsKrause** [comment]
@Angelk90 as described in the first post I tested the behaviour on a Google Pixel 4a with Android 12.

**Comment by Angelk90** [comment]
@NilsKrause : Tested on the emulator?

**Comment by NilsKrause** [comment]
Emulator and actual device

**Pull request merged**
