### PR TITLE
Add OCR frame processor plugin

### PR DESCRIPTION
**Pull request by aarongrider**
Replace existing, unimplemented frame processor plugin with new one.

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey thanks for the PR! Let's not remove @rodgomesc's plugin but instead only add your's directly below that

**Comment by rodgomesc** [comment]
hi i think we can remove my plugin, i still don't have time to implement this

**Comment by rodgomesc** [comment]
sorry for that guys, i’ll keep maintaining my other plugins :)

**Comment by mrousavy** [comment]
Cool, then LGTM!

**Pull request merged**
