### PR TITLE
fix: Handle video codec parameter from react in swift (#2109)

### LINKED ISSUE #2109: 🐛 videoCodec setting isn't used on iOS
### What's happening?

Setting videoCodec to 264 does not affect the codec. it's always 265

### Reproduceable Code

```tsx
camera.current?.startRecording({
      videoCodec: "h264",
      onRecordingError: console.error,
      onRecordingFinished: handleRecording,
})
```

### Relevant log output

```shell
–
```

### Camera Device

```json
ERROR  TypeError: Cannot convert undefined value to object

This error is located at:
    in observerComponent (created by observerComponent)
    in RCTView (created by View)
    in View (created by observerComponent)
    in observerComponent (created by CameraScreen)
    in RCTView (created by View)
    in View (created by ScreenWithoutScrolling)
    in RCTView (created by View)
    in View (created by ScreenWithoutScrolling)
    in ScreenWithoutScrolling (created by Screen)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
```

### Device

iPhone 15 Pro

### VisionCamera Version

3.6.3

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by yspreen**
## What

This PR handles video codecs in swift. Previously the parameter was ignored

## Changes

Turn options param into String; Use that string in getSettings method to set codec.

## Tested on

iPhone 15 Pro

## Related issues

- Fixes #2109

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey thanks for your PR, but this does not change the behaviour of the function at all as far as I can see.

I already fixed the issue you linked in a previous commit, but didn't release to npm yet.

**Comment by yspreen** [comment]
`codec = dictionary["videoCodec"] as? String`

does significantly change behavior. the parameter is never unpacked otherwise.
I do currently run on this fork bc it's critical for us to get this fixed please lmk once it's in npm

**Comment by mrousavy** [comment]
Either way, it's removing type safety here, and the separation of concern is in the wrong place. 
The value unpacking and parsing should happen in the type file, not dynamically in the record video file.

The correct fix is on main, I didn't test it yet since I didn't have the free time to dedicate to fixing your issues yet.
I might take a look at this soon to see if there was something missing in my quick fix.

**Comment by mrousavy** [comment]
This is the quick fix I did in my free time https://github.com/mrousavy/react-native-vision-camera/commit/cc65ec26a9ba68a9501fe14fc6f1b722368932e1

**Pull request closed without merging**
