### PR TITLE
fix: Fix "Folly" include

### LINKED ISSUE #195: 🐛 'folly/Optional.h' file not found on Xcode version 12.5
## What

Can't run on Xcode v12.5, it shows 'folly/Optional.h' file not found.
Not sure if it's related to https://github.com/facebook/flipper/issues/2215
### Logs

Screen Shot 2021-06-11 at 12 00 33 AM

## Reproducable sample

1. Create a new react native project
2. Install react-native-vision-camera 
3. Build and run on Xcode v12.5

## Environment

* Platform(s):
  * [V] iOS
  * [ ] Android
* react-native version: 0.63.4
* react-native-vision-camera version: 2.3.0
* react-native-reanimated version: N/A

### PR DESCRIPTION
**Pull request by mrousavy**
* fixes #195 
* fixes comment from #269

### CODE REVIEW

**Comment by mrousavy** [comment]
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `VisionCamera` depends upon `RCT-Folly`, which does not define modules.
To opt into those targets generating module maps (which is necessary to import them from Swift
when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or
specify `:modular_headers => true` for particular dependencies.
```
☹️ anyone knows if/how this can be fixed?

**Comment by matheusmatos** [comment]
Using your changes, I got a new error:

Captura de Tela 2021-07-12 às 14 34 45

**Comment by matheusmatos** [comment]
@mrousavy here is my suggestion to be merging: https://github.com/matheusmatos/react-native-vision-camera/commit/f0d652c00c48ee87f3450ca0734ea388380abadc. More details in https://github.com/mrousavy/react-native-vision-camera/issues/195#issuecomment-879422807.

Open to any questions!

**Comment by mrousavy** [comment]
@matheusmatos can you test again with my newest changes?

**Comment by pke** [comment]
This does not solve the problem in a RN 0.63.3 project.

**Pull request merged**
