### PR TITLE
Update kotlin version to 1.6.20

### PR DESCRIPTION
**Pull request by ozgurbayram**
## What
This PR fixes kotlin-android-extensions Gradle plugin version 1.6.20 and higher. issue

## Changes
This PR updated kotlin version to 1.6.20

## Tested on
Android simulator

## Related issues
https://github.com/mrousavy/react-native-vision-camera/issues/1477

### CODE REVIEW

**Comment by juliendevleeschauwer** [comment]
You can solve the issue by specify the kotlinVersion in the android/build.gradle file directy

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        kotlinVersion = "1.6.20" <--

**Comment by ozgurbayram** [comment]
> You can solve the issue by specify the kotlinVersion in the android/build.gradle file directy
> 
> buildscript { ext { buildToolsVersion = "33.0.0" kotlinVersion = "1.6.20" <--

Yeah, but i have to do it manually on every time i reinstall packages

**Comment by juliendevleeschauwer** [comment]
> 

No if you specify the kotlinVersion in your "app" android/build.gradle not  in nodeModules.

**Comment by cn-johndpope** [comment]
cool - working

```
android {
    buildscript {
        ext {
            buildToolsVersion = "33.0.0"
            kotlinVersion = "1.6.20"
        }
    }
```

**Comment by mrousavy** [comment]
Hey! Thanks but this has been overridden in V3. :/

**Pull request closed without merging**
