### PR TITLE
fix: Fix `VideoProfile` possibly being null

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Fixes the `Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getBitrate()' on a null object reference` error, which happened because `profiles.getVideoProfiles()` _could_ return an empty list.

### CODE REVIEW

**Comment by Romick2005** [comment]
Just linking full error output:

```
11-30 10:48:41.986 15280 15465 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mrousavy.camera.CameraViewManager

11-30 10:49:32.693 15280 15464 E ReactNativeJS: { userInfo: null,
11-30 10:49:32.693 15280 15464 E ReactNativeJS:   message: 'An unknown error occurred while trying to start a video recording! Attempt to invoke virtual method \'int android.media.EncoderProfiles$VideoProfile.getBitrate()\' on a null object reference',
11-30 10:49:32.693 15280 15464 E ReactNativeJS:   cause: 
11-30 10:49:32.693 15280 15464 E ReactNativeJS:    { stacktrace: 'java.lang.NullPointerException: Attempt to invoke virtual method \'int android.media.EncoderProfiles$VideoProfile.getBitrate()\' on a null object reference\n\tat fd.s.a(Unknown Source:0)\n\tat fd.v.b(Unknown Source:175)\n\tat com.mrousavy.camera.core.e.e(Unknown Source:19)\n\tat com.mrousavy.camera.core.e.<init>(Unknown Source:56)\n\tat com.mrousavy.camera.core.c.Z0(Unknown Source:206)\n\tat com.mrousavy.camera.h.c(Unknown Source:180)\n\tat com.mrousavy.camera.CameraViewModule$f.invokeSuspend(Unknown Source:68)\n\tat kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11)\n\tat af.x0.run(Unknown Source:93)\n\tat gf.a.Z(Unknown Source:0)\n\tat gf.a$c.d(Unknown Source:14)\n\tat gf.a$c.p(Unknown Source:28)\n\tat gf.a$c.run(Unknown Source:0)\n',
11-30 10:49:32.693 15280 15464 E ReactNativeJS:      message: 'Attempt to invoke virtual method \'int android.media.EncoderProfiles$VideoProfile.getBitrate()\' on a null object reference' },
11-30 10:49:32.693 15280 15464 E ReactNativeJS:   code: 'capture/unknown' }
```

**Comment by Fgabz** [comment]
Thanks for fix! While it's been release, is there a workaround for the problem ?

**Comment by mrousavy** [comment]
@Romick2005 just to be clear; the PR here fixes your issue? Or do you still have that error with this PR?

**Comment by Romick2005** [comment]
I applied this fix as patch, but still have this (or some other) issue on user side. It is hard to test for me as I do not have that device Xiaomi 11 Pro, on my Samsung S21+ and Huawei p20 pro it works fine.

**Comment by Romick2005** [comment]
> @Romick2005 just to be clear; the PR here fixes your issue? Or do you still have that error with this PR?

Now I got client device ). It is still there:
```
Short message: An unknown error occurred while trying to start a video recording! null.
 ERROR  {"cause": {"message": null, "stacktrace": "java.util.NoSuchElementException
	at com.mrousavy.camera.extensions.RecordingSession_getRecommendedBitRateKt.getRecommendedBitRate(RecordingSession+getRecommendedBitRate.kt:107)
	at com.mrousavy.camera.core.RecordingSession.getBitRate(RecordingSession.kt:132)
	at com.mrousavy.camera.core.RecordingSession.<init>(RecordingSession.kt:37)
	at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:532)
	at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:34)
	at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying to start a video recording! null", "userInfo": null}
```

**Comment by ZakirBangash** [comment]
I am facing this issue on Google pixel 6 pro

**Comment by aladin-bilalagic** [comment]
Got the same issue on Nothing Phone (1).
Latest version of react-native-vision-camera installed.

Same code works on iOS

**Comment by MRafayyy** [comment]
I am also facing the same issue on Oppo F9.

**Comment by mrousavy** [comment]
Maybe we need to filter formats by what is supported in the Video Profile. Can you post your stracktraces / logs here?

**Comment by MRafayyy** [comment]
I was getting this error:

ERROR {"cause": {"message": "Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getBitrate()' on a null object reference", "stacktrace": "java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getBitrate()' 
on a null object reference
    at com.mrousavy.camera.extensions.RecordingSession_getRecommendedBitRateKt.getRecommendedBitRate(RecordingSession+getRecommendedBitRate.kt:37)
    at com.mrousavy.camera.core.RecordingSession.getBitRate(RecordingSession.kt:132)
    at com.mrousavy.camera.core.RecordingSession.<init>(RecordingSession.kt:37)
    at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:532)
    at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:44)
    at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:91)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying to start a video recording! Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getBitrate()' on a null object reference", "userInfo": null}

-----------------------------------------------------------
Then I added KotlinVersion: "1.7.0" in my buld.gradle file:
buildscript {
    ext {
        kotlinVersion = "1.7.0"
        
 -----------------------------------------------------------------
 Then I was getting a different error this time:
 
 java.util.NoSuchElementException at com.mrousavy.camera.extensions.RecordingSession_getRecommendedBitRateKt.getRecommendedBitRate(RecordingSession+getRecommendedBitRate.kt:107)
 
 So I followed "Fix VideoProfile possibly being null #2231" and after applying those changes in node modules folder, I patched it and the error is gone now.

**Comment by ZakirBangash** [comment]
Thank you 💖, it has been resolved  on my pixel 6 pro

**Comment by mrousavy** [comment]
awesome !

**Pull request merged**
