### PR TITLE
Update FRAME_PROCESSOR_PLUGINS.mdx

### PR DESCRIPTION
**Pull request by gev2002**

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey, thanks for your contributions, and awesome work on creating that many plugins! 

Could you maybe update the text you added here to also mention which underlying technology your plugins use? I'm guessing it's all built on MLKit?

**Comment by mrousavy** [comment]
hey - bump here

**Comment by gev2002** [comment]
Yes, sorry, I was sick

**Comment by mrousavy** [comment]
Amazing, LGTM!

**Pull request merged**
