### PR TITLE
fix: restore support for v2 without frame processors

### PR DESCRIPTION
**Pull request by tomekzaw**
## What

This PR fixes problems mentioned in https://github.com/mrousavy/react-native-vision-camera/pull/1759#issuecomment-1723792052 and https://github.com/mrousavy/react-native-vision-camera/pull/1759#issuecomment-1724236912.

## Changes

* Restored support for RNVisionCamera v2 without frame processors (when react-native-reanimated is not installed):
    * Added proper detection if Reanimated 3.5.0+ is installed on Android in `build.gradle`
    * Moved contents of `FrameProcessorUtils.mm` back to `FrameProcessorRuntimeManager.mm` on iOS
* Bumped C++ version to 17 to resolve problems with missing `std::optional` when Reanimated is installed

## Tested on

iPhone simulator

## Related issues

Requires https://github.com/software-mansion/react-native-reanimated/pull/5098.

### CODE REVIEW

**Comment by mrousavy** [comment]
Whoops, you're right, I rushed a release on that I forgot that we still need to make this optional

**Comment by efstathiosntonas** [comment]
@mrousavy please check my review comment above, I believe `disableFrameProcessors` should be `VisionCamera_disableFrameProcessors`

**Comment by mrousavy** [comment]
Hey @efstathiosntonas - nope in this case not, only `disableFrameProcessors` is being queried - tested with that flag set and without.

```
VisionCamera: Frame Processors are disabled because the user explicitly disabled it ('disableFrameProcessors=true'). C++ part will not be built.
```

**Comment by efstathiosntonas** [comment]
perfect, thank you for your hard work guys ❤️

**Comment by Diego10x** [comment]
Is this what they're talking about? Why does the Frame Processor get disabled in my project?  :(

I just updated React Native from 0.70.5 to 0.71.0

`VisionCamera: Building with Hermes...
VisionCamera: Frame Processors are disabled because Reanimated 3.5.0+ is not installed` 

And it's strange because I have the following, and it does compile my app, but it doesn't open the camera because the frame processor is disabled:

```
"react-native-reanimated": "^2.10.0",
 "react-native-vision-camera": "^2.15.2",
 "vision-camera-code-scanner": "^0.2.0"
```
    
 Then I update and it gives me this.
 
```
 "react-native-reanimated": "^3.5.0",
 "react-native-vision-camera": "^2.16.1",
 "vision-camera-code-scanner": "^0.2.0"
```
 
```
VisionCamera: Building with Hermes...
VisionCamera: Frame Processors are enabled! Building C++ part...

What went wrong:
Execution failed for task :react-native-vision-camera:configureCMakeDebug[arm64-v8a].
[CXX1214] /Users/foxmaster/Documents/repos/canjeappv2/node_modules/react-native-vision-camera/android/CMakeLists.txt debug|arm64-v8a :
 User has minSdkVersion 21 but library was built for 26
 [//react-native-reanimated/reanimated] 
```
 
 PD. I apologize if my comment is out of place or has nothing to do with the topic. Regards.

**Comment by mrousavy** [comment]
Hey @Diego10x  - the error message tells you exactly what you need to do. You need Reanimated 3.5+, and you need minSdk 26+.

**Comment by Diego10x** [comment]
Thank you for your valuable work, it worked for me in the following way:

package.json:
```
"react-native": "^0.71.0",
"react-native-reanimated": "^3.5.0",
"react-native-vision-camera": "^2.15.2",
"vision-camera-code-scanner": "^0.2.0"
```

build.gradle:

```
 buildToolsVersion = "33.0.0"
 minSdkVersion = 21
 compileSdkVersion = 33
 targetSdkVersion = 33
```

Thanks.

**Comment by tomekzaw** [comment]
It definitely doesn't work with 2.15.2, please use RNVisionCamera `^2.16.1` along with Reanimated `^3.5.4`.
```
"react-native-reanimated": "^3.5.4",
"react-native-vision-camera": "^2.16.1",
```

**Pull request merged**
