### PR TITLE
fix: wrong orientation enum being send to ImageCapture

### PR DESCRIPTION
**Pull request by rodgomesc**

### CODE REVIEW

**Comment by mrousavy** [comment]
Ah nice catch, thanks @rodgomesc! Could you just run `yarn check-all` in `package` to format thhe Kotlin code?

**Comment by rodgomesc** [comment]
> package

hey,  yup i did that, it don't change anything

**Comment by rodgomesc** [comment]
uops wait i need to install some packages via homebrew

**Comment by rodgomesc** [comment]
done

**Comment by mrousavy** [comment]
Thanks!

**Pull request merged**
