### PR TITLE
fix: Add support for react-native 0.71

### LINKED ISSUE #1418: 🐛 Building android with React Native 0.71
### What were you trying to do?

Hello,

I am trying to build my application for android.
On iOS, it builds well and launches.

I use `react-native-reanimated` : `2.14.1`.

I get these warings and errors on the android build : 
```bash
> Configure project :react-native-vision-camera
VisionCamera: node_modules/ found at: /Users/***/node_modules
VisionCamera: Building with JSC...
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
VisionCamera: Frame Processors are enabled! Building C++ part...
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
```
```bash
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/***/node_modules/react-native-vision-camera/android/build.gradle' line: 279

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera'.
> Expected directory '/Users/***/node_modules/react-native/android' to contain exactly one file, however, it contains no files.
```

Any idea if vision-camera is ready for react-native 0.71?

Thank you for your work! 

### Reproduceable Code

_No response_

### What happened instead?

I get a gradle build error.

### Relevant log output

_No response_

### Device

Any

### VisionCamera Version

^2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by ChristophGr**
## What
Support for React-Native 0.71

This PR allows compiling when used in React-Native 0.71 apps

## Changes

Adapt android build to support changes to native library handling introduced in react-native 0.71

## Tested on
* Xiaomi Mi A3, Android 11 with React-Native 0.71 App

No Tests with older react-native versions were performed.

## Related issues

* Fixes #1418

### CODE REVIEW

**Comment by zzz08900** [comment]
I guess one can still disable hermes with 0.71, so maybe check if project.ext.react.enableHermes is set to false on 0.71 and above?

**Comment by Yunnathai** [comment]
@mrousavy check it, pls.

**Comment by mrousavy** [comment]
@ChristophGr wow, this is absolutely amazing! Thank you so much for your PR. 🙏 

I think it also makes sense to upgrade the example app to react-native 0.71, but this doesn't have to be part of this PR.

I'll test it in my apps and if nothing breaks, we're good to go!

**Comment by ChristophGr** [comment]
> I guess one can still disable hermes with 0.71, so maybe check if project.ext.react.enableHermes is set to false on 0.71 and above?

Yes you're right. I fixed the condition to reflect the changes in 0.71 properly

**Comment by mrousavy** [comment]
Thanks, looks like it's working for me! Released in 2.15.3

**Pull request merged**
