### PR TITLE
fix: Also properly convert `any[]` -> `List<Object>` in FP Android

### LINKED ISSUE #1754: 🐛 v3 (Android): Missing List<Object> case in convertJSIObjectToJNIMap
### What's happening?

I wanted to pass an array as the value for one of the options of a frame processor. It works on iOS, but not Android. Unfortunately, I am not too familiar with jsi/jni code to be able to submit a PR for this myself. I could probably put back the ReadableNativeArray stuff from the old code, but I'm guessing you had something else in mind for that.

### Reproduceable Code

```tsx
} else if (value.isObject()) {
      // Object

      auto valueAsObject = value.getObject(runtime);

      if (valueAsObject.isArray(runtime)) {
        // List<Object>
      } else if (valueAsObject.isHostObject(runtime)) {
        throw std::runtime_error("You can't pass HostObjects here.");
      } else {
        // Map<String, Object>

        auto map = convertJSIObjectToJNIMap(runtime, valueAsObject);
        hashMap->put(key, map);
      }
```

### Relevant log output

```shell
2023-09-02 09:38:40.764 25240-25240 ExamplePlugin           com.mrousavy.camera.example          D  1920 x 1080 Image with format #34. Logging 4 parameters:
2023-09-02 09:38:40.764 25240-25240 ExamplePlugin           com.mrousavy.camera.example          D    -> 42.0 (java.lang.Double)
2023-09-02 09:38:40.764 25240-25240 ExamplePlugin           com.mrousavy.camera.example          D    -> true (java.lang.Boolean)
2023-09-02 09:38:40.764 25240-25240 ExamplePlugin           com.mrousavy.camera.example          D    -> {test=0.0, second=test} (java.util.HashMap)
2023-09-02 09:38:40.764 25240-25240 ExamplePlugin           com.mrousavy.camera.example          D    -> hello! (java.lang.String)
```

### Camera Device

_No response_

### Device

Any Android

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [X] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Fixes #1754

### CODE REVIEW

**Comment by Syar-tech** [comment]
This PR fail to compile for me as a return is missing in JSIJNIConversion.cpp file  : 
image
The else clause should return hashMap I guess (line 73)

**Comment by rocket13011** [comment]
this line causes the app to crash:
``` return plugin.call(frame,{types:{0:QR_CODE"},checkInverted: true}); ```

while it passes through but is not detected as an Array on the other side.
``` return plugin.call(frame,{types:["QR_CODE"],checkInverted: true}); ```
return > params.toString() > ```{types=["QR_CODE"], checkInverted=true}```

**Comment by mrousavy** [comment]
Thanks @Syar-tech, fixed!


@rocket13011 sorry I don't get it. Share your full JS FP code

**Comment by rkmackinnon** [comment]
@rocket13011, The Android code for vision-camera-code-scanner is not fully updated yet. For e.g., createBarcodeInstance is still expecting ReadableNativeArray. This is probably incompatible with the new code in this PR and the real cause of any issues, rather in something in @mrousavy's code.

If you'd like to add a comment on my own PR with any findings feel free to do that here: https://github.com/rodgomesc/vision-camera-code-scanner/pull/139 or open an issue here: https://github.com/rkmackinnon/vision-camera-code-scanner.

**Comment by rocket13011** [comment]
it works with the return HashMap

@rkmackinnon I've completely rewritten the mlkit plugin.

I test it in lite mode:

```
@Override
  public Object callback(Frame frame, Map<String, Object> arguments) {
   Log.d('MLKitPlugin',arguments.tostring());
    return null;
  }
```
I'm still forwarding the PR you gave me to help it run smoothly if need be ;)

**Pull request merged**
