### PR TITLE
fix: barcode scanner crash

### PR DESCRIPTION
**Pull request by necmettindev**
## What

i've made changes that I believe fix the issue of crashes after barcode scans on android. i tested it with my device and didn't encounter any problems with this version.

### CODE REVIEW

**Comment by necmettindev** [comment]
@mrousavy is there any problem with merging?

**Comment by mrousavy** [comment]
Hey, thanks for your PR!

No, not yet - I'd have to test this to confirm this works.
It would help if other people that have this bug could test if this fixes it for them!

**Comment by mrousavy** [comment]
Can you link those issues that will be fixed by this PR? And maybe also ping some people from those issues to test this PR. Thanks!

**Comment by only1chi** [comment]
> Hey, thanks for your PR!
> 
> No, not yet - I'd have to test this to confirm this works. It would help if other people that have this bug could test if this fixes it for them!

@necmettindev I haven't been able to get my app to crash with barcode scanning after applying this change. Initially, my app would crash every once in a while after scanning a QR code.

**Comment by MehPhisto** [comment]
This is not solving the issue for ean-13

**Comment by only1chi** [comment]
> This is not solving the issue for ean-13

You are right! My testing was limited.

**Comment by MehPhisto** [comment]
Downgrading to v3.5.1 fixes the issue for me

**Comment by lBroth** [comment]
> This is not solving the issue for ean-13

Same here

**Comment by only1chi** [comment]
@MehPhisto @lBroth 

Have you tried this [PR](https://github.com/mrousavy/react-native-vision-camera/pull/2213)?

**Comment by lBroth** [comment]
> @MehPhisto @lBroth 
> 
> 
> 
> Have you tried this [PR](https://github.com/mrousavy/react-native-vision-camera/pull/2213)?

Not yet. I hope I can try it tonight

**Review by vonovak — COMMENTED** [review]
to be sure, I believe it'd be better to call `image.close()` only once on each image. That means it should be called in `onCancel` and `onComplete`. The way it's done at the time of this comment, the code calls it several times.

**Comment by mrousavy** [comment]
Hey - I already added this to the codebase now by only calling `close` once; in the completion callback. 

https://github.com/mrousavy/react-native-vision-camera/blob/2fb56e580253d240a0d7bf857c353f8bf96870fd/package/android/src/main/java/com/mrousavy/camera/core/CodeScannerPipeline.kt#L64

Thanks for your PR though!

**Pull request closed without merging**
