### PR TITLE
chore: bump kotlin to support 0.71

### LINKED ISSUE #1431: 🐛 The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher
### What were you trying to do?

I want build app using react-native-vision-camera: 2.15.2 for react-native 0.70.6

### Reproduceable Code

_No response_

### What happened instead?

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-actions-shortcuts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10

### Relevant log output

_No response_

### Device

Android

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by dcangulo**
## What

Does not build on blank React Native 0.71 project.

Will probably close #1431 and #1449

```
> Configure project :react-native-vision-camera
VisionCamera: node_modules/ found at: /Users/davidangulo/Desktop/mobile/latest/node_modules
VisionCamera: Building with JSC...
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
VisionCamera: Frame Processors are disabled because REA v2 does not exist. C++ part will not be built.
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-vision-camera' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30
```

## Changes

Bumped kotlin from `1.5.30` to `1.6.20`.

## Tested on

I tested the following code on Samsung Galaxy S20+

```jsx
import React, { useState } from 'react';
import { StyleSheet, PermissionsAndroid, Button } from 'react-native';
import { Camera, useCameraDevices } from 'react-native-vision-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(false);
  const devices = useCameraDevices();
  const device = devices.back;

  const requestCameraPermission = async () => {
    PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA, {
      title: 'Camera',
      message: 'Camera',
      buttonPositive: 'OK',
    }).then((granted) => {
      setHasPermission(granted === PermissionsAndroid.RESULTS.GRANTED);
    });
  };

  if (device == null || !hasPermission) {
    return <Button title='request camera permission' onPress={requestCameraPermission} />;
  }

  return (
    <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive
    />
  );
}
```

## Related issues

N/A

### CODE REVIEW

**Comment by erwanlpfr** [comment]
Hello, 

Does it build with only this change?
I opened another issue #1418 which displays another type of error.

If I have time, I'll try it out !

Thanks!

**Comment by unixvb** [comment]
any plans on releasing this?

**Comment by ghost** [comment]
> any plans on releasing this?

any news?

**Review by KarlosQ — APPROVED** [review]

**Comment by praveen-kaia** [comment]
Hi, Any update on when this change is going to merge ?

**Pull request closed without merging**
