### PR TITLE
#2995 Fix duplicate label in when.

### PR DESCRIPTION
**Pull request by Romick2005**
## What

Does not build on latest react-native 0.74.2 with npx react-native run-android command, but works fine on RN 73.8

```
> Task :react-native-vision-camera:compileDebugKotlin
w: file:///Users/romick/app/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/types/OutputOrientation.kt:17:9 Duplicate label in when
w: file:///Users/romick/app/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/utils/CamcorderProfileUtils.kt:66:42 'get(Int, Int): CamcorderProfile!' is deprecated. Deprecated in Java
w: file:///Users/romick/app/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/utils/CamcorderProfileUtils.kt:90:42 'get(Int, Int): CamcorderProfile!' is deprecated. Deprecated in Java

> Task :app:compileDebugJavaWithJavac FAILED
545 actionable tasks: 541 executed, 4 up-to-date
```

Please remove duplicated [lines](https://github.com/mrousavy/react-native-vision-camera/blob/main/package/android/src/main/java/com/mrousavy/camera/core/types/OutputOrientation.kt#L17C52-L17C53):

image

### Reproduceable Code

```tsx
Regular project on latest RN 0.74.2.
```

### Relevant log output

```shell
> Task :react-native-vision-camera:compileDebugKotlin
w: file:///Users/romick/app/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/types/OutputOrientation.kt:17:9 Duplicate label in when
w: file:///Users/romick/app/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/utils/CamcorderProfileUtils.kt:66:42 'get(Int, Int): CamcorderProfile!' is deprecated. Deprecated in Java
w: file:///Users/romick/app/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/utils/CamcorderProfileUtils.kt:90:42 'get(Int, Int): CamcorderProfile!' is deprecated. Deprecated in Java

> Task :app:compileDebugJavaWithJavac FAILED
545 actionable tasks: 541 executed, 4 up-to-date
```

## Changes

Fix duplicate label in when

## Tested on
    * Huawai P20, Android 10

## Related issues
#2995

### CODE REVIEW

**Comment by mrousavy** [comment]
bro lol

thank you for your contribution, but clearly this is a typo, there is 4 orientations and clearly I meant to use landscape_right instead of landscape_left here. 

Please change this to use landscape_right.

**Comment by Romick2005** [comment]
> bro lol
> 
> thank you for your contribution, but clearly this is a typo, there is 4 orientations and clearly I meant to use landscape_right instead of landscape_left here.
> 
> Please change this to use landscape_right.

Yeah, I didn't dive deeper in the code. Just fixed the annoying warning ).

Done. Please check.

**Comment by mrousavy** [comment]
Hey so I'm not sure why you changed a lot of other things in the file now including the order of the enum cases, but both CIs failed. It doesn't build anymore (because the `;` is placed wrong), and it doesn't lint properly. I'm just gonna fix this in a new PR, thanks anyways!

**Comment by Romick2005** [comment]
I can fix that ). Done.

**Pull request closed without merging**
